name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      TURBO_TELEMETRY_DISABLED: 1
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint code
        run: |
          yarn lint
          yarn format:check
      - name: Build project
        run: yarn build
